
title: Hongyu Chen's Homepage
page-top-title: Hongyu Chen
top-section-bg-text: A Computational Social Scientist with Love in Text Data
home-subtitle: Hongyu Chen&ensp;|&ensp;陈虹宇 (MS.c)
copyright-text: '&copy; Hongyu Chen 2024. All Rights Reserved.'
